version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: react-app
    path: ""
    image-resources: true
    text-resources:
      - path: "*.tsx"
        format: react-hardcoded
